// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/golang-class/lab/app"
	"github.com/golang-class/lab/connector"
	"github.com/golang-class/lab/database"
	"github.com/golang-class/lab/handler"
	"github.com/golang-class/lab/repository"
	"github.com/golang-class/lab/service"
)

// Injectors from provider.go:

func InitializeApp() *app.App {
	movieAPIConnector := connector.NewRealMovieAPI()
	movieService := service.NewRealMovieService(movieAPIConnector)
	pool := database.NewDatabasePool()
	favoriteRepository := repository.NewRealFavoriteRepository(pool)
	favoriteService := service.NewRealFavoriteService(favoriteRepository)
	handlerHandler := handler.NewHandler(movieService, favoriteService)
	appApp := app.NewApp(handlerHandler)
	return appApp
}
